/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoacademia;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodsilva
 */
public class TelaRelatorios extends javax.swing.JFrame {

    
    DefaultTableModel defTable;
    /**
     * Creates new form TelaRelatorios
     */
    public TelaRelatorios() {
        initComponents();
        txtCategoria.setVisible(false);
            lblNomeCliente.setVisible(false);
            lblSexoCliente.setVisible(false);
            lblPlanoCliente.setVisible(false);
        txtCategoria.setVisible(false);
        lblPlanoCliente.setVisible(false);
        defTable = (DefaultTableModel) tblClientes.getModel();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        lblTipoRelatorio = new javax.swing.JLabel();
        cmbTipoRelatorio = new javax.swing.JComboBox<>();
        txtCategoria = new javax.swing.JTextField();
        lblPlanoCliente = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lblNomeCliente = new javax.swing.JLabel();
        lblSexoCliente = new javax.swing.JLabel();

        setTitle("Tela de Relatorios");
        getContentPane().setLayout(null);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data Nascimento", "Sexo", "Cpf", "Email", "Endereço", "Contato", "Plano"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 920, 320);

        lblTipoRelatorio.setText("Tipo de Relatório");
        getContentPane().add(lblTipoRelatorio);
        lblTipoRelatorio.setBounds(10, 10, 110, 50);

        cmbTipoRelatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Por Sexo", "Por Nome", "Por Plano", " " }));
        cmbTipoRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbTipoRelatorio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoRelatorioItemStateChanged(evt);
            }
        });
        cmbTipoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipoRelatorio);
        cmbTipoRelatorio.setBounds(120, 20, 160, 30);
        getContentPane().add(txtCategoria);
        txtCategoria.setBounds(440, 20, 140, 30);

        lblPlanoCliente.setText("Digite o plano desejado");
        getContentPane().add(lblPlanoCliente);
        lblPlanoCliente.setBounds(290, 20, 160, 30);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(610, 20, 140, 30);

        lblNomeCliente.setText("Nome do cliente");
        getContentPane().add(lblNomeCliente);
        lblNomeCliente.setBounds(300, 20, 120, 30);

        lblSexoCliente.setText("Digite o sexo desejado");
        getContentPane().add(lblSexoCliente);
        lblSexoCliente.setBounds(290, 20, 103, 30);

        setSize(new java.awt.Dimension(929, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoRelatorioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoRelatorioItemStateChanged
        String tipo;
        tipo = cmbTipoRelatorio.getSelectedItem().toString();
        if(tipo.equalsIgnoreCase("Por Sexo")){
            txtCategoria.setVisible(true);
            lblSexoCliente.setVisible(true);
            lblNomeCliente.setVisible(false);
            lblPlanoCliente.setVisible(false);
            
            defTable.setRowCount(0);
        }else if(tipo.equalsIgnoreCase("Por nome")){
            txtCategoria.setVisible(true);
            lblNomeCliente.setVisible(true);
            lblSexoCliente.setVisible(false);
            lblPlanoCliente.setVisible(false);

            defTable.setRowCount(0);
            }else if(tipo.equalsIgnoreCase("Por Plano")){
            txtCategoria.setVisible(true);
            lblNomeCliente.setVisible(false);
            lblSexoCliente.setVisible(false);
            lblPlanoCliente.setVisible(true);
            defTable.setRowCount(0);
        }else if(tipo.equalsIgnoreCase("Geral")){
            txtCategoria.setVisible(false);
            lblNomeCliente.setVisible(false);
            lblSexoCliente.setVisible(false);
            lblPlanoCliente.setVisible(false);
            defTable.setRowCount(0);
        }
            
    }//GEN-LAST:event_cmbTipoRelatorioItemStateChanged

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //1 - Pegar o conteúdo do combo de tipo de relatório
        String tipoRelatorio;
        tipoRelatorio = cmbTipoRelatorio.getSelectedItem().toString();
        //2 - Conectar com o Banco de dados
        try {
            Connection conexao;
            PreparedStatement st;
            ResultSet resultado;

            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancoacademia", "root", "09041448abner");
            //Verifica o conteúdo do comboBox de tipo de relatório
            if (tipoRelatorio.equalsIgnoreCase("Geral")) {
                st = conexao.prepareStatement("SELECT * FROM tb_cliente");
                resultado = st.executeQuery();

                defTable.setRowCount(0);
                while (resultado.next()) {
                    Object[] linha = {resultado.getString("nm_completo"), resultado.getString("dt_nascimento"), resultado.getString("sexo"), resultado.getString("cpf"),resultado.getString("email"),resultado.getString("endereco"),resultado.getString("contato"),resultado.getString("tp_plano")};
                    defTable.addRow(linha);
                }
            } else if (tipoRelatorio.equalsIgnoreCase("Por Sexo")) {
                st = conexao.prepareStatement("SELECT * FROM tb_cliente WHERE sexo LIKE ?");
                st.setString(1, "%" + txtCategoria.getText() + "%");
                resultado = st.executeQuery();

                defTable.setRowCount(0);
                while (resultado.next()) {
                    Object[] linha = {resultado.getString("nm_completo"), resultado.getString("dt_nascimento"), resultado.getString("sexo"), resultado.getString("cpf"),resultado.getString("email"),resultado.getString("endereco"),resultado.getString("contato"),resultado.getString("tp_plano")};
                    defTable.addRow(linha);
                }
            } else if (tipoRelatorio.equalsIgnoreCase("Por nome")) {
                st = conexao.prepareStatement("SELECT * FROM tb_cliente WHERE nm_completo LIKE ?");
                st.setString(1, "%" + txtCategoria.getText() + "%");
                resultado = st.executeQuery();

                defTable.setRowCount(0);
                while (resultado.next()) {
                    Object[] linha = {resultado.getString("nm_completo"), resultado.getString("dt_nascimento"), resultado.getString("sexo"), resultado.getString("cpf"),resultado.getString("email"),resultado.getString("endereco"),resultado.getString("contato"),resultado.getString("tp_plano")};
                    defTable.addRow(linha);
                }
                } else if (tipoRelatorio.equalsIgnoreCase("Por Plano")) {
                st = conexao.prepareStatement("SELECT * FROM tb_cliente WHERE tp_plano LIKE ?");
                st.setString(1, "%" + txtCategoria.getText() + "%");
                resultado = st.executeQuery();

                defTable.setRowCount(0);
                while (resultado.next()) {
                    Object[] linha = {resultado.getString("nm_completo"), resultado.getString("dt_nascimento"), resultado.getString("sexo"), resultado.getString("cpf"),resultado.getString("email"),resultado.getString("endereco"),resultado.getString("contato"),resultado.getString("tp_plano")};
                    defTable.addRow(linha);
                }
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto" + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbTipoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoRelatorioActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbTipoRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblPlanoCliente;
    private javax.swing.JLabel lblSexoCliente;
    private javax.swing.JLabel lblTipoRelatorio;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtCategoria;
    // End of variables declaration//GEN-END:variables
}
