/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoacademia;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rodsilva
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu(String usuario, String cargo) {
        initComponents();
        pnlCadastrarUsuario.setVisible(false);
        pnlCadastrarCliente.setVisible(false);
        lblSaudacao.setText("Bem-vindo(a), " + usuario);
        //btnExcluir.setVisible(false);
        if (cargo.equalsIgnoreCase("Faxineiro") || cargo.equalsIgnoreCase("Personal")|| (cargo.equalsIgnoreCase("Professor de Jiu jitsu"))){
            habilitar();
        }
    }
    

    
    
     public TelaMenu(String cargo) {
        initComponents();
    }

    private TelaMenu() {
        initComponents();
    }
    
    
    private void habilitar() {
        jmnCadastrarFuncionarios.setVisible(false);
        jmnCadastrarClientes.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        pnlCadastrarUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDtNascimento = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNomeCompleto = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        cmbCargo = new javax.swing.JComboBox<>();
        txtCPF = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        txtEndereco = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JToggleButton();
        pswRepitaSenha = new javax.swing.JPasswordField();
        pswSenha = new javax.swing.JPasswordField();
        lblSaudacao = new javax.swing.JLabel();
        cbmCliente = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        pnlCadastrarCliente = new javax.swing.JPanel();
        lblDadosCadastrais = new javax.swing.JLabel();
        txtDtNascimentoCliente = new javax.swing.JTextField();
        txtEmailCliente = new javax.swing.JTextField();
        txtNomeCompletoCliente = new javax.swing.JTextField();
        txtContatoCliente = new javax.swing.JTextField();
        cmbTipoPlanoCliente = new javax.swing.JComboBox<>();
        txtCPFCliente = new javax.swing.JTextField();
        cmbSexoCliente = new javax.swing.JComboBox<>();
        txtEnderecoCliente = new javax.swing.JTextField();
        btnSalvarCliente = new javax.swing.JToggleButton();
        lblSaudacao1 = new javax.swing.JLabel();
        cbmCliente1 = new javax.swing.JComboBox<>();
        btnBuscarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnFuncionarios = new javax.swing.JMenu();
        jmnCadastrarFuncionarios = new javax.swing.JMenuItem();
        jmnAlterarFuncionario = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmnClientes = new javax.swing.JMenu();
        jmnCadastrarClientes = new javax.swing.JMenuItem();
        jmnAlterarClientes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmnTreinos = new javax.swing.JMenu();
        jmnTreinosTipos = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setTitle("TelaMenu");
        getContentPane().setLayout(null);

        pnlCadastrarUsuario.setLayout(null);

        jLabel1.setText("Dados Cadastrais");
        pnlCadastrarUsuario.add(jLabel1);
        jLabel1.setBounds(230, 20, 120, 20);

        txtDtNascimento.setText("Data de nascimento");
        txtDtNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtNascimentoActionPerformed(evt);
            }
        });
        pnlCadastrarUsuario.add(txtDtNascimento);
        txtDtNascimento.setBounds(360, 50, 220, 30);

        txtEmail.setText("E-mail");
        pnlCadastrarUsuario.add(txtEmail);
        txtEmail.setBounds(360, 89, 220, 30);

        txtNomeCompleto.setText("Nome Completo");
        pnlCadastrarUsuario.add(txtNomeCompleto);
        txtNomeCompleto.setBounds(10, 50, 340, 30);

        txtContato.setText("Contato");
        pnlCadastrarUsuario.add(txtContato);
        txtContato.setBounds(240, 130, 180, 30);

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diretor", "Gerente", "Recepcionista", "Personal", "Faxineiro", "Professor de Jiu jitsu", "Professor de Muay Thai", "Professor de Zumba" }));
        pnlCadastrarUsuario.add(cmbCargo);
        cmbCargo.setBounds(430, 130, 150, 30);

        txtCPF.setText("CPF");
        pnlCadastrarUsuario.add(txtCPF);
        txtCPF.setBounds(10, 89, 220, 30);

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Não Binario", " " }));
        pnlCadastrarUsuario.add(cmbSexo);
        cmbSexo.setBounds(240, 89, 110, 30);

        txtEndereco.setText("Endereço");
        pnlCadastrarUsuario.add(txtEndereco);
        txtEndereco.setBounds(10, 130, 220, 30);

        txtUsuario.setText("Usuario");
        pnlCadastrarUsuario.add(txtUsuario);
        txtUsuario.setBounds(10, 170, 180, 30);

        btnSalvar.setText("Criar Cadastro");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlCadastrarUsuario.add(btnSalvar);
        btnSalvar.setBounds(10, 220, 160, 30);

        pswRepitaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswRepitaSenhaActionPerformed(evt);
            }
        });
        pnlCadastrarUsuario.add(pswRepitaSenha);
        pswRepitaSenha.setBounds(400, 170, 180, 30);
        pnlCadastrarUsuario.add(pswSenha);
        pswSenha.setBounds(200, 170, 190, 30);

        lblSaudacao.setText("jLabel2");
        pnlCadastrarUsuario.add(lblSaudacao);
        lblSaudacao.setBounds(460, 310, 130, 13);

        cbmCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente" }));
        pnlCadastrarUsuario.add(cbmCliente);
        cbmCliente.setBounds(430, 130, 150, 30);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlCadastrarUsuario.add(btnBuscar);
        btnBuscar.setBounds(180, 220, 80, 30);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        pnlCadastrarUsuario.add(btnExcluir);
        btnExcluir.setBounds(280, 220, 80, 30);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        pnlCadastrarUsuario.add(btnAlterar);
        btnAlterar.setBounds(380, 220, 90, 30);

        getContentPane().add(pnlCadastrarUsuario);
        pnlCadastrarUsuario.setBounds(0, 0, 620, 360);

        pnlCadastrarCliente.setLayout(null);

        lblDadosCadastrais.setText("Dados Cadastrais");
        pnlCadastrarCliente.add(lblDadosCadastrais);
        lblDadosCadastrais.setBounds(230, 20, 120, 20);

        txtDtNascimentoCliente.setText("Data de nascimento");
        txtDtNascimentoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtNascimentoClienteActionPerformed(evt);
            }
        });
        pnlCadastrarCliente.add(txtDtNascimentoCliente);
        txtDtNascimentoCliente.setBounds(360, 50, 220, 30);

        txtEmailCliente.setText("E-mail");
        pnlCadastrarCliente.add(txtEmailCliente);
        txtEmailCliente.setBounds(360, 89, 220, 30);

        txtNomeCompletoCliente.setText("Nome Completo");
        pnlCadastrarCliente.add(txtNomeCompletoCliente);
        txtNomeCompletoCliente.setBounds(10, 50, 340, 30);

        txtContatoCliente.setText("Contato");
        pnlCadastrarCliente.add(txtContatoCliente);
        txtContatoCliente.setBounds(240, 130, 180, 30);

        cmbTipoPlanoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plano Bronze", "Plano Prata", "Plano Ouro", "Gym Pass" }));
        pnlCadastrarCliente.add(cmbTipoPlanoCliente);
        cmbTipoPlanoCliente.setBounds(430, 130, 150, 30);

        txtCPFCliente.setText("CPF");
        pnlCadastrarCliente.add(txtCPFCliente);
        txtCPFCliente.setBounds(10, 89, 220, 30);

        cmbSexoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Não Binario", " " }));
        pnlCadastrarCliente.add(cmbSexoCliente);
        cmbSexoCliente.setBounds(240, 89, 110, 30);

        txtEnderecoCliente.setText("Endereço");
        pnlCadastrarCliente.add(txtEnderecoCliente);
        txtEnderecoCliente.setBounds(10, 130, 220, 30);

        btnSalvarCliente.setText("Criar Cadastro");
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });
        pnlCadastrarCliente.add(btnSalvarCliente);
        btnSalvarCliente.setBounds(80, 190, 160, 30);

        lblSaudacao1.setText("jLabel2");
        pnlCadastrarCliente.add(lblSaudacao1);
        lblSaudacao1.setBounds(460, 310, 130, 13);

        cbmCliente1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente" }));
        pnlCadastrarCliente.add(cbmCliente1);
        cbmCliente1.setBounds(430, 130, 150, 30);

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        pnlCadastrarCliente.add(btnBuscarCliente);
        btnBuscarCliente.setBounds(250, 190, 80, 30);

        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });
        pnlCadastrarCliente.add(btnExcluirCliente);
        btnExcluirCliente.setBounds(350, 190, 80, 30);

        btnAlterarCliente.setText("Alterar");
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });
        pnlCadastrarCliente.add(btnAlterarCliente);
        btnAlterarCliente.setBounds(450, 190, 90, 30);

        getContentPane().add(pnlCadastrarCliente);
        pnlCadastrarCliente.setBounds(0, 0, 620, 360);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/academia 2.jpg"))); // NOI18N
        lblImagem.setText("jLabel3");
        getContentPane().add(lblImagem);
        lblImagem.setBounds(0, -7, 620, 370);

        jmnFuncionarios.setText("Funcionarios");

        jmnCadastrarFuncionarios.setText("Cadastrar");
        jmnCadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnCadastrarFuncionariosActionPerformed(evt);
            }
        });
        jmnFuncionarios.add(jmnCadastrarFuncionarios);

        jmnAlterarFuncionario.setText("Alterar");
        jmnAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAlterarFuncionarioActionPerformed(evt);
            }
        });
        jmnFuncionarios.add(jmnAlterarFuncionario);

        jMenuItem3.setText("Relatorios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmnFuncionarios.add(jMenuItem3);

        jMenuBar1.add(jmnFuncionarios);

        jmnClientes.setText("Clientes");

        jmnCadastrarClientes.setText("Cadastrar");
        jmnCadastrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnCadastrarClientesActionPerformed(evt);
            }
        });
        jmnClientes.add(jmnCadastrarClientes);

        jmnAlterarClientes.setText("Alterar");
        jmnAlterarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAlterarClientesActionPerformed(evt);
            }
        });
        jmnClientes.add(jmnAlterarClientes);

        jMenuItem2.setText("Relatorios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmnClientes.add(jMenuItem2);

        jMenuBar1.add(jmnClientes);

        jmnTreinos.setText("Treinos");

        jmnTreinosTipos.setText("Treinos Tipos");
        jmnTreinosTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnTreinosTiposActionPerformed(evt);
            }
        });
        jmnTreinos.add(jmnTreinosTipos);

        jMenuBar1.add(jmnTreinos);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(636, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancoacademia", "root", "09041448abner");
            if (pswSenha.getText().equals(pswRepitaSenha.getText())) {
                st = conexao.prepareStatement("INSERT INTO tb_usuario VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

                st.setString(1, txtNomeCompleto.getText());
                st.setString(2, txtUsuario.getText());
                st.setString(3, pswSenha.getText());
                st.setString(4, txtDtNascimento.getText());
                st.setString(5, cmbSexo.getSelectedItem().toString());
                st.setString(6, txtCPF.getText());
                st.setString(7, txtEmail.getText());
                st.setString(8, txtEndereco.getText());
                st.setString(9, txtContato.getText());
                st.setString(10, cmbCargo.getSelectedItem().toString());
                st.executeUpdate(); //Executa o comando INSERT
                JOptionPane.showMessageDialog(btnSalvar, "Dados salvos com sucesso");
                txtUsuario.setText("");
                pswSenha.setText("");
                pswRepitaSenha.setText("");
                txtUsuario.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "As senhas não coincidem");
                pswSenha.requestFocus();
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(btnSalvar, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(btnSalvar, "Algum parâmetro do BD está incorreto");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtDtNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtNascimentoActionPerformed

    private void jmnCadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnCadastrarFuncionariosActionPerformed
         pnlCadastrarUsuario.setVisible(true);
         pnlCadastrarCliente.setVisible(false);
         cbmCliente.setVisible(false);
         cmbCargo.setVisible(true);
          btnBuscar.setVisible(false);
          btnSalvar.setVisible(true);
    }//GEN-LAST:event_jmnCadastrarFuncionariosActionPerformed

    private void jmnCadastrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnCadastrarClientesActionPerformed
       pnlCadastrarCliente.setVisible(true);
       pnlCadastrarUsuario.setVisible(false);
       cbmCliente.setVisible(true);
       cmbCargo.setVisible(false);
       btnBuscar.setVisible(false);
       btnSalvar.setVisible(true);
       
    }//GEN-LAST:event_jmnCadastrarClientesActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
if (txtCPF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o cpf corretamente");
            txtCPF.requestFocus();
            return; // para a execução nesta linha (stop)       
        }
        try {
            Connection conexao;
            PreparedStatement st;
            ResultSet resultado;
            
            //Conexão com o BD
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancoacademia", "root", "09041448abner");
            //Busca o produto na tabela produtos do BD
            st = conexao.prepareStatement("SELECT * FROM tb_usuario WHERE cpf=?");
            st.setString(1, txtCPF.getText());
            resultado = st.executeQuery(); //Executa o SELECT criado acima
            if (resultado.next()) { // Se encontrou o código do produto na tabela
                txtNomeCompleto.setText(resultado.getString("nm_completo"));
                txtUsuario.setText(resultado.getString("usuario"));
                pswSenha.setText(resultado.getString("senha"));
                txtDtNascimento.setText(resultado.getString("dt_nascimento"));
                cmbSexo.setSelectedItem(resultado.getString("sexo"));
                txtEmail.setText(resultado.getString("email"));
                txtEndereco.setText(resultado.getString("endereco"));
                txtContato.setText(resultado.getString("contato"));
                cmbCargo.setSelectedItem(resultado.getString("cargo"));
            
                btnSalvar.setVisible(true);
                btnBuscar.setVisible(true);
            } else { //Senão encontrou o produto
                JOptionPane.showMessageDialog(null, "Produto n”ao encontrado");
                txtCPF.requestFocus();
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto");
        }
    
                                        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jmnAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAlterarFuncionarioActionPerformed
       btnBuscar.setVisible(true);
       btnSalvar.setVisible(false);
       pnlCadastrarUsuario.setVisible(true);
       pnlCadastrarCliente.setVisible(false);
    }//GEN-LAST:event_jmnAlterarFuncionarioActionPerformed

    private void jmnAlterarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAlterarClientesActionPerformed
       btnBuscar.setVisible(true);
       btnSalvar.setVisible(false);
       pnlCadastrarCliente.setVisible(true);
       pnlCadastrarUsuario.setVisible(false);
    }//GEN-LAST:event_jmnAlterarClientesActionPerformed

    private void pswRepitaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswRepitaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswRepitaSenhaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       try {
            //CONECTAR COM O BANCO DE DADOS
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancoacademia", "root", "admin");
            // DELETAR O PRODUTO PELO CÓDIGO INFORMADO
            st = conexao.prepareStatement("DELETE FROM tb_usuario WHERE cpf=?");
            st.setString(1, txtCPF.getText());
            int res = st.executeUpdate();
            //VERIFICAR SE O PRODUTO FOI OU NÃO DELETADO E INFORMAR
            if (res == 1) { // Se excluiu da tabela
                JOptionPane.showMessageDialog(null, "Produto excluído com sucesso");
                txtNomeCompleto.setText("");
                txtDtNascimento.setText("");
                txtCPF.setText("");
                cmbSexo.setSelectedItem("");
                txtEmail.setText("");
                txtEndereco.setText("");
                txtContato.setText("");
                cmbCargo.setSelectedItem("");
                txtUsuario.setText("");
                pswSenha.setText("");
                txtCPF.requestFocus();
                btnExcluir.setVisible(false);
                btnAlterar.setVisible(false);
            } else { // Se não excluiu da tabela
                JOptionPane.showMessageDialog(null, "Não foi possível excluir o produto com este código");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto" + ex.getMessage());
        }



     
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
try {
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.jdbc.Driver");
     conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancoacademia", "root", "admin");
            st = conexao.prepareStatement("UPDATE tb_usuario SET nm_completo = ?, dt_nascimento = ?, sexo = ?, email = ?, endereco = ?, contato = ?, cargo = ?  WHERE cpf = ?");
            st.setString(1, txtNomeCompleto.getText());
            st.setString(2, txtDtNascimento.getText());
            st.setString(3, cmbSexo.getSelectedItem().toString());
            st.setString(4, txtEmail.getText());
            st.setString(5, txtEndereco.getText());
            st.setString(6, txtContato.getText());
            st.setString(7, cmbCargo.getSelectedItem().toString());
            st.setString(8, txtCPF.getText());
            st.executeUpdate(); //Executa o comando SQL UPDATE
            JOptionPane.showMessageDialog(null,"Alteração realizada com sucesso");
            txtNomeCompleto.setText("");
            txtDtNascimento.setText("");
            cmbSexo.setSelectedItem("");
            txtEmail.setText("");
            txtEndereco.setText("");
            txtContato.setText("");
            cmbCargo.setSelectedItem("");
             btnExcluir.setVisible(false);
             btnAlterar.setVisible(false);
    } catch (ClassNotFoundException ex) {
        	JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex.getMessage());
    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto" + ex.getMessage());
    }        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void jmnTreinosTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnTreinosTiposActionPerformed
       TelaTreinos tela;
      tela = new TelaTreinos();
      tela.setVisible(true);  
    }//GEN-LAST:event_jmnTreinosTiposActionPerformed

    private void txtDtNascimentoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtNascimentoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtNascimentoClienteActionPerformed

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
try {
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancoacademia", "root", "09041448abner");
                  
                st = conexao.prepareStatement("INSERT INTO tb_cliente VALUES(?, ?, ?, ?, ?, ?, ?, ?)");
                st.setString(1, txtNomeCompletoCliente.getText());
                st.setString(2, txtDtNascimentoCliente.getText());
                st.setString(3, cmbSexoCliente.getSelectedItem().toString());
                st.setString(4, txtCPFCliente.getText());
                st.setString(5, txtEmailCliente.getText());
                st.setString(6, txtEnderecoCliente.getText());
                st.setString(7, txtContatoCliente.getText());
                st.setString(8, cmbTipoPlanoCliente.getSelectedItem().toString());
                st.executeUpdate(); //Executa o comando INSERT
                JOptionPane.showMessageDialog(btnSalvarCliente, "Dados salvos com sucesso");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(btnSalvarCliente, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(btnSalvarCliente, "Algum parâmetro do BD está incorreto");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
    if (txtCPFCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o cpf corretamente");
            txtCPFCliente.requestFocus();
            return; // para a execução nesta linha (stop)       
        }
        try {
            Connection conexao;
            PreparedStatement st;
            ResultSet resultado;
            
            //Conexão com o BD
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancoacademia", "root", "admin");
            //Busca o produto na tabela produtos do BD
            st = conexao.prepareStatement("SELECT * FROM tb_cliente WHERE cpf=?");
            st.setString(1, txtCPFCliente.getText());
            resultado = st.executeQuery(); //Executa o SELECT criado acima
            if (resultado.next()) { // Se encontrou o código do produto na tabela
                txtNomeCompletoCliente.setText(resultado.getString("nm_completo"));
                txtDtNascimentoCliente.setText(resultado.getString("dt_nascimento"));
                cmbSexoCliente.setSelectedItem(resultado.getString("sexo"));
                txtEmailCliente.setText(resultado.getString("email"));
                txtEnderecoCliente.setText(resultado.getString("endereco"));
                txtContatoCliente.setText(resultado.getString("contato"));
                cmbTipoPlanoCliente.setSelectedItem(resultado.getString("tp_plano"));
                btnSalvarCliente.setVisible(true);
                btnBuscarCliente.setVisible(true);
            } else { //Senão encontrou o produto
                JOptionPane.showMessageDialog(null, "Cliente não encontrado");
                txtCPFCliente.requestFocus();
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
try {
            //CONECTAR COM O BANCO DE DADOS
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancoacademia", "root", "admin");
            // DELETAR O PRODUTO PELO CÓDIGO INFORMADO
            st = conexao.prepareStatement("DELETE FROM tb_cliente WHERE cpf=?");
            st.setString(1, txtCPFCliente.getText());
            int res = st.executeUpdate();
            //VERIFICAR SE O PRODUTO FOI OU NÃO DELETADO E INFORMAR
            if (res == 1) { // Se excluiu da tabela
                JOptionPane.showMessageDialog(null, "Cliente excluido com Sucesso!");
                txtNomeCompletoCliente.setText("");
                txtDtNascimentoCliente.setText("");
                txtCPFCliente.setText("");
                cmbSexoCliente.setSelectedItem("");
                txtEmailCliente.setText("");
                txtEnderecoCliente.setText("");
                txtContatoCliente.setText("");
                cmbTipoPlanoCliente.setSelectedItem("");
                btnExcluir.setVisible(false);
                btnAlterar.setVisible(false);
            } else { // Se não excluiu da tabela
                JOptionPane.showMessageDialog(null, "Não foi possível excluir o produto com este código");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto" + ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed
       try {
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.jdbc.Driver");
     conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancoacademia", "root", "admin");
            st = conexao.prepareStatement("UPDATE tb_cliente SET nm_completo = ?, dt_nascimento = ?, sexo = ?, email = ?, endereco = ?, contato = ?, tp_plano = ?  WHERE cpf = ?");
            st.setString(1, txtNomeCompletoCliente.getText());
            st.setString(2, txtDtNascimentoCliente.getText());
            st.setString(3, cmbSexoCliente.getSelectedItem().toString());
            st.setString(4, txtEmailCliente.getText());
            st.setString(5, txtEnderecoCliente.getText());
            st.setString(6, txtContatoCliente.getText());
            st.setString(7, cmbTipoPlanoCliente.getSelectedItem().toString());
            st.setString(8, txtCPFCliente.getText());
            st.executeUpdate(); //Executa o comando SQL UPDATE
            JOptionPane.showMessageDialog(null,"Alteração realizada com sucesso");
            txtNomeCompletoCliente.setText("");
            txtDtNascimentoCliente.setText("");
            cmbSexoCliente.setSelectedItem("");
            txtEmailCliente.setText("");
            txtEnderecoCliente.setText("");
            txtContatoCliente.setText("");
            cmbTipoPlanoCliente.setSelectedItem("");
             btnExcluirCliente.setVisible(false);
             btnAlterarCliente.setVisible(false);
    } catch (ClassNotFoundException ex) {
        	JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex.getMessage());
    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto" + ex.getMessage());
    }        
    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaRelatorios tela;
        tela = new TelaRelatorios();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaRelatoriosFuncionarios telaFuncinarios;
        telaFuncinarios = new TelaRelatoriosFuncionarios();
        telaFuncinarios.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JToggleButton btnSalvarCliente;
    private javax.swing.JComboBox<String> cbmCliente;
    private javax.swing.JComboBox<String> cbmCliente1;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JComboBox<String> cmbSexoCliente;
    private javax.swing.JComboBox<String> cmbTipoPlanoCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jmnAlterarClientes;
    private javax.swing.JMenuItem jmnAlterarFuncionario;
    private javax.swing.JMenuItem jmnCadastrarClientes;
    private javax.swing.JMenuItem jmnCadastrarFuncionarios;
    private javax.swing.JMenu jmnClientes;
    private javax.swing.JMenu jmnFuncionarios;
    private javax.swing.JMenu jmnTreinos;
    private javax.swing.JMenuItem jmnTreinosTipos;
    private javax.swing.JLabel lblDadosCadastrais;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblSaudacao;
    private javax.swing.JLabel lblSaudacao1;
    private javax.swing.JPanel pnlCadastrarCliente;
    private javax.swing.JPanel pnlCadastrarUsuario;
    private javax.swing.JPasswordField pswRepitaSenha;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCPFCliente;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtContatoCliente;
    private javax.swing.JTextField txtDtNascimento;
    private javax.swing.JTextField txtDtNascimentoCliente;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEnderecoCliente;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JTextField txtNomeCompletoCliente;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
